name: Weekly Calendar Updater

on:
  schedule:
    - cron: '0 0 * * 1'  # 毎週月曜日の00:00（UTC）
  workflow_dispatch:     # 手動実行も可能

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python main.py

      - name: Debug Output
        if: failure()
        run: echo "❌ スクリプト実行に失敗しました"

